### ISSUE TITLE
More attack types

### ISSUE THREAD

**Issue by PushkarOP** [diamond-gold/MiniBosses#25]
Different types of attack:

- guardian attack
- a custom particle attack that can shoot player even player is not near them
- Blast

**Comment by SiahRBLX** [comment]
added the [Feature Request] label @PushkarOP

**Comment by diamond-gold** [comment]
Could you elaborate more on what is "can shoot player even player is not near them" ?
And what is "Blast" ?

**Comment by PushkarOP** [comment]
> Could you elaborate more on what is "can shoot player even player is not near them" ? And what is "Blast" ?

I mean can shoot like arrow

And blast like, npc will come to player and blast like Creeper

**Comment by diamond-gold** [comment]
So it will be something like a projectile but instead of entity it is displayed using particles?

**Comment by PushkarOP** [comment]
> So it will be something like a projectile but instead of entity it is displayed using particles?

Yes

**Comment by diamond-gold** [comment]
How is the bouncing attack different from the current attack? Other than the jumping action which should not be tied with attacking

**Comment by PushkarOP** [comment]
Isn't that possible that mob will jump and damag player, like slime?

**Comment by diamond-gold** [comment]
Tested to be working as of [fe49ad3](https://github.com/diamond-gold/MiniBosses/commit/fe49ad3ca6a257965faca76e490f24b4bab2fdb6)

Slime jumping attack
```yaml
slime:
  x: 280
  "y": 4
  z: 280
  world: FLAT
  networkId: minecraft:slime
  movesByJumping: true
  drops: slimeball;0;1; slimeball;0;1;;50 slimeball;0;1;;50 # drops 1-3 slimeballs
  speed: 0.5
  gravity: 0.01
  jumpStrength: 3
  scale: 5
  attackDamage: 5
  range: 50
  hurtModifiers:
    4: 0 #no fall damage
```
Creeper blast
```yaml
creeper:
  x: 270
  "y": 4
  z: 270
  world: FLAT
  networkId: minecraft:creeper
  drops: gunpowder;0;1;;50
  attackDamage: 0
  range: 50
  speed: 0.5
  projectiles:
  - fireRangeMin: 0
    fireRangeMax: 2
    speed: 1
    attackRate: 10
    attackDamage: 0
    explodeRadius: 5
    explodeDestroyBlocks: false
    health: 5
    canBeAttacked: false
    despawnAfter: 20
    gravity: 0
    particle: minecraft:endrod
```
Guardian laser
```yaml
guardian:
  x: 290
  "y": 4
  z: 290
  world: FLAT
  networkId: minecraft:guardian
  movesByJumping: true
  jumpStrength: 1
  speed: 0.5
  drops: fish
  gravity: 0.01
  attackDamage: 5 # melee
  scale: 2
  range: 50
  armor: # for thorns, will not show
  - minecraft:diamond_helmet;0;1;{ench:[{id:5s,lvl:5s}]}
  projectiles: # actual laser damage
  - fireRangeMin: 0
    fireRangeMax: 20
    speed: 10
    attackRate: 100
    attackDamage: 1
    health: 5
    canBeAttacked: false
    followNearest: true # 100% hit unless behind a block
    despawnAfter: 100
    gravity: 0
    particle: minecraft:endrod
```
